#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mkosi
Version  : 4
Release  : 11
URL      : https://github.com/systemd/mkosi/archive/v4.tar.gz
Source0  : https://github.com/systemd/mkosi/archive/v4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: mkosi-bin
Requires: mkosi-python3
Requires: mkosi-license
Requires: mkosi-python
Requires: bmap-tools-bin
BuildRequires : buildreq-distutils3

%description
# mkosi - Create legacy-free OS images
A fancy wrapper around `dnf --installroot`, `debootstrap`,
`pacstrap` and `zypper` that may generate disk images with a number of
bells and whistles.

%package bin
Summary: bin components for the mkosi package.
Group: Binaries
Requires: mkosi-license

%description bin
bin components for the mkosi package.


%package license
Summary: license components for the mkosi package.
Group: Default

%description license
license components for the mkosi package.


%package python
Summary: python components for the mkosi package.
Group: Default
Requires: mkosi-python3

%description python
python components for the mkosi package.


%package python3
Summary: python3 components for the mkosi package.
Group: Default
Requires: python3-core

%description python3
python3 components for the mkosi package.


%prep
%setup -q -n mkosi-4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532992196
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mkosi
cp LICENSE %{buildroot}/usr/share/doc/mkosi/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mkosi

%files license
%defattr(-,root,root,-)
/usr/share/doc/mkosi/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
